# base image
FROM node:alpine

# set working directory
WORKDIR '/app'

COPY package.json .

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install

COPY . .

# start app
CMD ["npm", "run", "start"]

